---

- name: Systemd_resolved tasks
  tags:
    - systemd_resolved_install
    - systemd_resolved_config
    - systemd_resolved_service
    - systemd_resolved
  block:
    - name: Set dependency variables
      ansible.builtin.include_vars: "{{ item }}"
      loop:
        - "{{ ansible_os_family }}/{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_os_family }}.yml"
    - name: Installation tasks
      ansible.builtin.import_tasks: install.yml
    - name: Configration tasks
      ansible.builtin.import_tasks: config.yml
    - name: Dropin configration tasks
      ansible.builtin.import_tasks: dropin.yml
    - name: Service tasks
      ansible.builtin.import_tasks: service.yml
  rescue:
    - name: Print Error
      ansible.builtin.debug:
        msg: "Unsupport platform or error occurred due to some reason."
      failed_when: true
